name: Build macOS App

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (optional)'
        required: false
        default: ''

jobs:
  build-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]
        build-type: [intel, universal]
        include:
          - build-type: intel
            build-command: dist:mac
            artifact-suffix: intel
          - build-type: universal
            build-command: dist:mac-universal
            artifact-suffix: universal
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Disable npm cache for now since package-lock.json is not in the expected location
        # cache: 'npm'
        # cache-dependency-path: 'projet-gestion-maitre/package-lock.json'
    
    - name: Setup Python (for native modules)
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        # Install only essential dependencies for native modules
        brew install pkg-config cairo pango
        # Skip optional dependencies to reduce build time

    # Disable node_modules cache to avoid Node.js version conflicts
    # - name: Cache node modules
    #   uses: actions/cache@v3
    #   with:
    #     path: projet-gestion-maitre/node_modules
    #     key: ${{ runner.os }}-node-${{ hashFiles('projet-gestion-maitre/package.json') }}
    #     restore-keys: |
    #       ${{ runner.os }}-node-

    - name: Install dependencies
      working-directory: ./projet-gestion-maitre
      run: |
        # Clean any existing node_modules and package-lock to avoid version conflicts
        rm -rf node_modules package-lock.json

        # Install dependencies fresh
        npm install

        # EXPERT SOLUTION: Complete native modules recompilation
        echo "🔧 Complete recompilation of native modules for Node.js v18..."

        # Install electron-rebuild globally for proper native module compilation
        npm install -g electron-rebuild

        # Force complete recompilation of all native modules
        echo "Rebuilding all native modules..."
        npx electron-rebuild --force --types prod,dev,optional

        # Alternative: Manual rebuild with specific Node.js version
        echo "Manual rebuild for Node.js v18..."
        npm rebuild --build-from-source

        # Verify native modules are working after rebuild
        echo "🧪 Testing native modules after rebuild..."
        node -e "
          try {
            const Database = require('better-sqlite3');
            const db = new Database(':memory:');
            console.log('✅ better-sqlite3 working correctly');
            db.close();
          } catch (e) {
            console.error('❌ better-sqlite3 still failing:', e.message);
            process.exit(1);
          }
        "

        # Setup macOS build environment
        npm run setup:macos

    - name: Build CSS
      working-directory: ./projet-gestion-maitre
      run: npm run build-css

    - name: Prepare clean database
      working-directory: ./projet-gestion-maitre
      run: |
        echo "🗄️ Preparing clean database with rebuilt native modules..."

        # EXPERT FALLBACK: Try multiple approaches for database creation
        echo "🔄 Attempting database creation with multiple fallback strategies..."

        # Strategy 1: Direct script execution
        echo "Strategy 1: Direct script execution..."
        if npm run create-clean-db; then
          echo "✅ Database created successfully with direct script"
        else
          echo "❌ Strategy 1 failed, trying Strategy 2..."

          # Strategy 2: Manual database creation with error handling
          echo "Strategy 2: Manual database creation..."
          node -e "
            const path = require('path');
            const fs = require('fs');

            console.log('🔧 Manual database creation fallback...');

            try {
              // Try to load better-sqlite3 with detailed error info
              const Database = require('better-sqlite3');
              console.log('✅ better-sqlite3 loaded successfully');

              // Create database directory
              const dbDir = path.join(__dirname, 'database');
              if (!fs.existsSync(dbDir)) {
                fs.mkdirSync(dbDir, { recursive: true });
              }

              // Create clean database
              const cleanDbPath = path.join(dbDir, 'main-clean.db');
              if (fs.existsSync(cleanDbPath)) {
                fs.unlinkSync(cleanDbPath);
              }

              const db = new Database(cleanDbPath);
              console.log('✅ Database file created successfully');

              // Create basic table structure
              db.exec(\`
                PRAGMA foreign_keys = ON;
                CREATE TABLE IF NOT EXISTS products (
                  id INTEGER PRIMARY KEY AUTOINCREMENT,
                  name TEXT NOT NULL,
                  price_retail REAL NOT NULL,
                  stock INTEGER NOT NULL DEFAULT 0
                );
              \`);

              db.close();
              console.log('✅ Clean database created successfully with fallback method');

            } catch (error) {
              console.error('❌ All strategies failed:', error.message);
              console.error('Creating empty database file as last resort...');

              // Last resort: create empty file
              const dbDir = path.join(__dirname, 'database');
              if (!fs.existsSync(dbDir)) {
                fs.mkdirSync(dbDir, { recursive: true });
              }
              fs.writeFileSync(path.join(dbDir, 'main-clean.db'), '');
              console.log('⚠️ Empty database file created - will be initialized at runtime');
            }
          "
        fi
    
    - name: Build macOS app (${{ matrix.build-type }})
      working-directory: ./projet-gestion-maitre
      run: npm run ${{ matrix.build-command }}
      env:
        NODE_ENV: production
        # Disable code signing for now (can be enabled later with certificates)
        CSC_IDENTITY_AUTO_DISCOVERY: false
        # Optimize build for CI
        ELECTRON_BUILDER_CACHE: /tmp/electron-builder-cache
    
    - name: List build artifacts
      working-directory: ./projet-gestion-maitre
      run: |
        echo "Build artifacts:"
        ls -la dist/
        if [ -d "dist/mac" ]; then
          echo "macOS build contents:"
          ls -la dist/mac/
        fi
        if [ -d "dist/mac-universal" ]; then
          echo "macOS universal build contents:"
          ls -la dist/mac-universal/
        fi
    
    - name: Upload macOS artifacts (${{ matrix.artifact-suffix }})
      uses: actions/upload-artifact@v4
      with:
        name: gestionpro-macos-${{ matrix.artifact-suffix }}-${{ github.sha }}
        path: |
          projet-gestion-maitre/dist/*.dmg
          projet-gestion-maitre/dist/*.zip
          projet-gestion-maitre/dist/mac/**/*
          projet-gestion-maitre/dist/mac-universal/**/*
        retention-days: 30
    
    - name: Upload build logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-macos-${{ github.sha }}
        path: |
          projet-gestion-maitre/npm-debug.log*
          projet-gestion-maitre/yarn-error.log*
        retention-days: 7
